export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const SET_SELECTED_BRANDS = "SET_SELECTED_BRANDS";
export const SET_SELECTED_MODELS = "SET_SELECTED_MODELS";
export const SEARCH_BRAND = "SEARCH_BRAND";
export const SEARCH_MODEL = "SEARCH_MODEL";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";

export const SET_SELECTED_SORT_TYPE = "SET_SELECTED_SORT_TYPE";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";

export const ADD_TO_CART = "ADD_TO_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
